-- Allow 'ui_review' as a message kind.
--
-- The kind column carries a CHECK constraint listing the kinds the UI knows how to
-- render, which is the right way round: a kind nothing can draw should not be
-- storable. It does mean adding one is a migration, and without this the first
-- ui_review result would fail its insert and strand the run.
--
-- The old constraint is found in the catalog rather than dropped by name. It was
-- declared inline in CREATE TABLE, so its name was generated by Postgres — almost
-- certainly message_kind_check, but a DROP CONSTRAINT IF EXISTS guessing wrong would
-- silently succeed and leave the original in place, still rejecting the new kind. The
-- symptom would be a run stranded on its first UI review, which is a long way from
-- the cause.
DO $$
DECLARE name text;
BEGIN
    FOR name IN
        SELECT con.conname
          FROM pg_constraint con
          JOIN pg_class rel ON rel.oid = con.conrelid
         WHERE rel.relname = 'message'
           AND con.contype = 'c'
           AND pg_get_constraintdef(con.oid) LIKE '%kind%'
    LOOP
        EXECUTE format('ALTER TABLE message DROP CONSTRAINT %I', name);
    END LOOP;
END $$;

ALTER TABLE message ADD CONSTRAINT message_kind_check
    CHECK (kind IN ('plan', 'review', 'ui_review', 'ask_human', 'notice'));
